services:
  webserver:
    image: samuelflavin/samuel.flavin:webserver 
    build: ./webserver
    ports:
      - 443:443
    configs:
      - sites.conf 
    secrets:
      - pub.cer
      - pri_key.key
    volumes:
      - content:/var/www/

volumes:
  content:

secrets:
  pub.cer:
    file: ./.secrets/pub.cer
  pri_key.key:
    file: ./.secrets/pri_key.key

configs:
  sites.conf:
    file: ./webserver/conf/deploy/sites.conf
