services:
  webserver:
    image: sflavin.registry.jetbrains.space/p/sflavin-nginx-server/containers/webserver:latest
    build: ./webserver
    ports:
      - 443:443
    configs:
      - name 
    secrets:
      - certs/pub.cer
      - certs/pri_key.key
    volumes:
      - content:/var/www/

volumes:
  content:

secrets:
  certs/pub.cer:
    file: ./.secrets/pub.cer
  certs/pri_key.key:
    file: ./.secrets/pri_key.key

configs:
  name:
    file: ./webserver/conf/deploy/sites.conf
